#!/bin/bash

# Download, build and install start script
go get -u -v github.com/couchbaselabs/couchbase-server-docker/scripts/couchbase-start && cd $GOPATH/src/github.com/couchbaselabs/couchbase-server-docker/scripts/couchbase-start && git checkout -t origin/support/0.2 && go build && cp couchbase-start /usr/local/bin && couchbase-start "$@"
