#!/bin/bash

# This script updates the couchbase-cluster binary to the latest master branch version
# so that the docker image doesn't have to be rebuilt each time.

if [[ -n "$UPDATE_COUCHBASE_CLUSTER_GO" ]] ; then
    echo "Updating couchbase-cluster-go to latest master branch"
    go get -u -v github.com/tleyden/couchbase-cluster-go/...
fi

cd $GOPATH/src/github.com/tleyden/couchbase-cluster-go/cmd/couchbase-cluster && godep go install 
couchbase-cluster "$@"

